apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

configMapGenerator:
- name: dashboard-edge-nodes
  files:
  - dashboards/edge_nodes.json
  options:
    labels:
      grafana_dashboard: ""
