{
 "title": "Edge Nodes",
 "tags": [ "edgefarm.monitor" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{job=\"node_exporter\", sysname!=\"Darwin\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"node_exporter\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\",job=\"node_exporter\"}",
     "legendFormat": "RAM"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$instance\",job=\"node_exporter\"}",
     "legendFormat": "SWAP"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\",job=\"node_exporter\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance\",job=\"node_exporter\"} - node_boot_time_seconds{instance=\"$instance\",job=\"node_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"node_exporter\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$instance\",job=\"node_exporter\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"node_exporter\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  (1 - sum without (mode) (rate(node_cpu_seconds_total{job=\"node_exporter\", mode=~\"idle|iowait|steal\", instance=\"$instance\"}[$__interval])))\n/ ignoring(cpu) group_left\n  count without (cpu, mode) (node_cpu_seconds_total{job=\"node_exporter\", mode=\"idle\", instance=\"$instance\"})\n)\n",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Average Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 4 },
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance\", job=\"node_exporter\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=\"$instance\", job=\"node_exporter\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=\"$instance\", job=\"node_exporter\"}",
     "legendFormat": "15m"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"node_exporter\", instance=\"$instance\"}) /\n  avg(node_memory_MemTotal_bytes{job=\"node_exporter\", instance=\"$instance\"})\n* 100\n)\n"
    },
    {
     "expr": "100 -\n(\n  avg(node_memory_SwapAvailable_bytes{job=\"node_exporter\", instance=\"$instance\"}) /\n  avg(node_memory_SwapTotal_bytes{job=\"node_exporter\", instance=\"$instance\"})\n* 100\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node_exporter\", instance=\"$instance\"}\n-\n  node_memory_MemFree_bytes{job=\"node_exporter\", instance=\"$instance\"}\n-\n  node_memory_Buffers_bytes{job=\"node_exporter\", instance=\"$instance\"}\n-\n  node_memory_Cached_bytes{job=\"node_exporter\", instance=\"$instance\"}\n)\n",
     "legendFormat": "mem used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node_exporter\", instance=\"$instance\"}",
     "legendFormat": "mem buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node_exporter\", instance=\"$instance\"}",
     "legendFormat": "mem cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter\", instance=\"$instance\"}",
     "legendFormat": "mem free"
    },
    {
     "expr": "node_memory_SwapFree_bytes{job=\"node_exporter\", instance=\"$instance\"}",
     "legendFormat": "swap free"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"node_exporter\", instance=\"$instance\"} - node_memory_SwapFree_bytes{job=\"node_exporter\", instance=\"$instance\"}",
     "legendFormat": "swap used"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_SwapAvailable_bytes{job=\"node_exporter\", instance=\"$instance\"}) /\n  avg(node_memory_SwapTotal_bytes{job=\"node_exporter\", instance=\"$instance\"})\n* 100\n)\n"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"node_exporter\", instance=\"$instance\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[5m])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"node_exporter\", instance=\"$instance\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[5m])",
     "legendFormat": "{{device}} written"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"node_exporter\", instance=\"$instance\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[5m])",
     "legendFormat": "{{device}} io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node_filesystem_size_bytes{job=\"node_exporter\", instance=\"$instance\", fstype!=\"\", mountpoint!=\"\"})\n"
    },
    {
     "expr": "max by (mountpoint) (node_filesystem_avail_bytes{job=\"node_exporter\", instance=\"$instance\", fstype!=\"\", mountpoint!=\"\"})\n"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Network Received",
   "type": "timeseries",
   "description": "Network received (bits/s)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node_exporter\", instance=\"$instance\", device!=\"lo\"}[$__interval]) * 8",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "timeseries",
   "description": "Network transmitted (bits/s)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node_exporter\", instance=\"$instance\", device!=\"lo\"}[$__interval]) * 8",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Hardware Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Hardware temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$instance\", job=\"node_exporter\"} > 0",
     "legendFormat": "{{chip}}-{{sensor}}"
    }
   ]
  }
 ]
}